In [2]:
import numpy as np
import qutip as qu

In [51]:
n = 3

z = np.array([[],[1],[1,1]])

j = 3

print(z[j-1])

[1, 1]


In [54]:
zj = qu.Qobj([z[j-1]])
V = qu.identity(j-1)
print(V)

r = np.linalg.norm(zj, ord=2)
c = np.cos(r)
s = np.sin(r)
z_u = zj.unit()

print(z_u)

zm = z_u.dag() * z_u

print(zm)



V = V - (1-c)*zm
print(V)

print('--------------------')

W = np.zeros((j,j))


W[0:j-1,0:j-1] = V
print(W)
W[0:j-1, j-1] = s*z_u
W[j-1, 0:j-1] = -s*z_u.conj()
W[j-1,j-1] = c
print('dfhkajsdf')
print(W)
W = qu.Qobj(W)
print(W)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.5 0.5]
 [0.5 0.5]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.57797185 -0.42202815]
 [-0.42202815  0.57797185]]
--------------------
[[ 0.57797185 -0.42202815  0.        ]
 [-0.42202815  0.57797185  0.        ]
 [ 0.          0.          0.        ]]
dfhkajsdf
[[ 0.57797185 -0.42202815  0.698456  ]
 [-0.42202815  0.57797185  0.698456  ]
 [-0.698456   -0.698456    0.15594369]]
Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = False
Qobj data =
[[ 0.57797185 -0.42202815  0.698456  ]
 [-0.42202815  0.57797185  0.698456  ]
 [-0.698456   -0.698456    0.15594369]]


/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:24: ComplexWarning: Casting complex values to real discards the imaginary part
/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:26: ComplexWarning: Casting complex values to real discards the imaginary part
/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:27: ComplexWarning: Casting complex values to real discards the imaginary part


In [55]:
print(W.dag() * W)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
def compute_V(n, j, z):
    z_u = qu.Qobj(z).unit()
    r = np.linalg.norm(z, ord=2)
    c = np.cos(r)
    s = np.sin(r)
    
    W = qu.identity(j-1) - (1-c)*z_u * z_u.dag()
    
    V = np.zeros((n,n))
    V[0:j-1,0:j-1] = W
    V[0:j-1, j-1] = s*z_u.trans()
    V[j-1, 0:j-1] = -s*z_u.conj().trans()
    V[j-1,j-1] = c
    
    V[j:,j:] = np.identity(n-j)
    
    
    return qu.Qobj(V)

In [8]:
V = compute_V(10, 3, np.array([1.,1.]))
print(V)
print(V.isunitary)
print(V.dag() * V)

Quantum object: dims = [[10], [10]], shape = (10, 10), type = oper, isherm = False
Qobj data =
[[ 0.57797185 -0.42202815  0.698456    0.          0.          0.
   0.          0.          0.          0.        ]
 [-0.42202815  0.57797185  0.698456    0.          0.          0.
   0.          0.          0.          0.        ]
 [-0.698456   -0.698456    0.15594369  0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   1.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          1.   

/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  # Remove the CWD from sys.path while we load stuff.
/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: ComplexWarning: Casting complex values to real discards the imaginary part
  # This is added back by InteractiveShellApp.init_path()
/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:12: ComplexWarning: Casting complex values to real discards the imaginary part
  if sys.path[0] == '':


In [184]:
n = 4

V_arr = []

z_arr = [[],[1.],[1.,1.],[1.,1.,1.]]

U_n = qu.identity(n)

for j in range(2, n + 1):
    zj = np.array(z_arr[j-1])
    # V_arr.append(compute_V(n, j, zj))
#
    A_j = compute_V(n, j, zj)

    U_n = A_j * U_n

# print(U_n*U_n.dag())

D = np.diag([0.5, 0.1, 0.1, 0.3])
D = qu.Qobj(D)

rho = U_n * D * U_n.dag()

rho.isherm, rho.tr()

/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  # Remove the CWD from sys.path while we load stuff.
/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: ComplexWarning: Casting complex values to real discards the imaginary part
  # This is added back by InteractiveShellApp.init_path()
/home/oliverkn/cloud/eth/2020_FS/spq/pycharm/venv/lib/python3.7/site-packages/ipykernel_launcher.py:12: ComplexWarning: Casting complex values to real discards the imaginary part
  if sys.path[0] == '':


(True, 1.0000000000000002)

In [194]:
S = qu.Qobj(rho, dims=[[2,2], [2,2]])
rho_in = [[0.9,0],[0,0.1]]
rho_in = qu.Qobj(rho_in)

qu.ptrace(qu.tensor(rho_in.trans(), qu.identity(2)) * S, 0)



Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.64599099 0.10005367]
 [0.01111707 0.02822322]]

In [178]:
def apply_choi(rho_in, rho_choi, dim_a):
    return dim_a * qu.ptrace(qu.tensor(rho_in.trans(), qu.identity(2)) * rho_choi, 1)

def apply_super(op, super_op):
    return qu.vector_to_operator(super_op * qu.operator_to_vector(op))

#construct S


def op_basis(n, k):
    b = np.zeros((n,n))
    b[k%n,k//n]=1
    return qu.Qobj(b)

S = np.zeros((4,4))

rho = qu.Qobj(rho, dims=[[2,2], [2,2]])

for i in range(n):
    b = op_basis(2, i)
    b_post = apply_choi(b, rho, 2)
    print(b_post)

# op0 = np.zeros((2,2))
# op0[0,0]=1
# op0 = qu.Qobj(op0)
# op0 = qu.operator_to_vector(op0)
# op0


Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.6219395  -0.24595121]
 [-0.24595121  0.81359603]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.20102044  0.03836232]
 [-0.08160244  0.02132103]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.20102044 -0.08160244]
 [ 0.03836232  0.02132103]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.34721781 -0.04755831]
 [-0.04755831  0.21724666]]


In [176]:
rho = qu.Qobj(rho, dims=[[2,2], [2,2]])
print(rho)
rho_a = 1/2 * qu.identity(2)

print(apply_choi(rho_a, rho, 2))



S = rho.dual_chan()
print(S)
print(apply_super(rho_a, S))



Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.31096975 -0.1229756   0.10051022 -0.04080122]
 [-0.1229756   0.40679802  0.01918116  0.01066052]
 [ 0.10051022  0.01918116  0.17360891 -0.02377916]
 [-0.04080122  0.01066052 -0.02377916  0.10862333]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.48457865 -0.14675476]
 [-0.14675476  0.51542135]]
Quantum object: dims = [[[2, 2], [2, 2]], [[2, 2], [2, 2]]], shape = (16, 16), type = super, isherm = True, superrep = choi
Qobj data =
[[ 9.67021843e-02 -3.82416924e-02  3.12556385e-02 -1.26879448e-02
  -3.82416924e-02  1.26501876e-01  5.96476031e-03  3.31509821e-03
   3.12556385e-02  5.96476031e-03  5.39871176e-02 -7.39459805e-03
  -1.26879448e-02  3.31509821e-03 -7.39459805e-03  3.37785698e-02]
 [-3.82416924e-02  1.51229990e-02 -1.23603053e-02  5.01755453e-03
   1.51229990e-02 -5.00262315e-02 -2.35881465e-03 -1.31098348e-03
  -1.23603053e-02 -2.

TypeError: Incompatible Qobj shapes

In [149]:
def apply_super(op, super_op):
    return qu.vector_to_operator(super_op * qu.operator_to_vector(op))

X = qu.sigmax()
Y = qu.sigmay()
S = qu.sprepost(X, Y)

rho = qu.rand_dm(2)
print(rho)
print(X*rho*Y)

print(apply_super(rho, S))

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.41097152 0.        ]
 [0.         0.58902848]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.58902848j 0.+0.j        ]
 [0.+0.j         0.-0.41097152j]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.+0.58902848j 0.+0.j        ]
 [0.+0.j         0.-0.41097152j]]


In [187]:
def apply_choi(rho_in, rho_choi, dim_a):
    return dim_a * qu.ptrace(qu.tensor(rho_in.trans(), qu.identity(2)) * rho_choi, 0)

S = qu.Qobj(rho, dims=[[2,2], [2,2]])

print(S.tr())

rho_a = [[0.9,0],[0,0.1]]
rho_a = qu.Qobj(rho_a)
print(rho_a)
print(apply_choi(rho_a, S, 2))

1.0000000000000002
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.9 0. ]
 [0.  0.1]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[1.29198197 0.20010733]
 [0.02223415 0.05644645]]


In [114]:

rho = 2*rho
print(rho)
print(rho.tr())


S = qu.Qobj(2*rho, dims=[[[2],[2]], [[2],[2]]], type='super', superrep='choi')
print(S)

S = qu.choi_to_super(S)
print(S)

S.iscp, S.istp, S.iscptp



Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.55890164 -0.30898907  0.1273786  -0.08060001]
 [-0.30898907  0.75055817 -0.03527953  0.02232346]
 [ 0.1273786  -0.03527953  0.32183589  0.04945908]
 [-0.08060001  0.02232346  0.04945908  0.3687043 ]]
2.0
Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[ 1.11780327 -0.61797814  0.25475719 -0.16120003]
 [-0.61797814  1.50111634 -0.07055906  0.04464691]
 [ 0.25475719 -0.07055906  0.64367179  0.09891816]
 [-0.16120003  0.04464691  0.09891816  0.7374086 ]]
Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = False
Qobj data =
[[ 1.11780327  0.25475719  0.25475719  0.64367179]
 [-0.61797814 -0.16120003 -0.07055906  0.09891816]
 [-0.61797814 -0.07055906 -0.16120003  0.09891816]
 [ 1.50111634  0.04464691  0.04464691  0.7374086 ]]


(True, False, False)

In [115]:
psi = qu.basis(2, 0)
rho = qu.ket2dm(psi)

vec_rho = qu.operator_to_vector(rho)

print(vec_rho)

vec_rho = S * vec_rho

print(vec_rho)

rho = qu.vector_to_operator(vec_rho)
print(rho)

Quantum object: dims = [[[2], [2]], [1]], shape = (4, 1), type = operator-ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
Quantum object: dims = [[[2], [2]], [1]], shape = (4, 1), type = operator-ket
Qobj data =
[[ 1.11780327]
 [-0.61797814]
 [-0.61797814]
 [ 1.50111634]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.11780327 -0.61797814]
 [-0.61797814  1.50111634]]


In [116]:
rho = 1/4* np.identity(4)
rho = qu.Qobj(rho, dims=[[[2],[2]], [[2],[2]]], type='super', superrep='choi')
print(rho)

rho.iscptp

# S = qu.choi_to_super(rho)
# 
# S.iscp, S.istp, S.iscptp


Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[0.25 0.   0.   0.  ]
 [0.   0.25 0.   0.  ]
 [0.   0.   0.25 0.  ]
 [0.   0.   0.   0.25]]


False

In [104]:
X = qu.sigmax()
S = qu.sprepost(X, X)

rho = qu.super_to_choi(S)
print(rho)
rho.tr()

S2 = qu.choi_to_super(rho)
print(S2)

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]
Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
