In [1]:
import numpy as np
import qutip as q

In [14]:
N = 2
dims = [2] * N

H = q.qzero(dimensions=dims)
H = H + N/2. * q.identity(dims)

sx, sy, sz = q.sigmax(), q.sigmay(), q.sigmaz()

H = H - q.tensor(sx, sx)
H = H - q.tensor(sy, sy)
H = H - q.tensor(sz, sz)

print(H)
print(H.eigenenergies())
print(H.eigenstates())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.]
 [ 0.  2. -2.  0.]
 [ 0. -2.  2.  0.]
 [ 0.  0.  0.  0.]]
[0. 0. 0. 4.]
(array([0.00000000e+00, 0.00000000e+00, 2.22044605e-15, 4.00000000e+00]), array([Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]],
       Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [-0.70710678]
 [ 0.70710678]
 [ 0.        ]]], dtype=object))


In [17]:
psi_0 =q.tensor(q.basis(2,0), q.basis(2,1))
print(psi_0)


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]


In [19]:
t_arr = np.linspace(0,0.4,10)
res = q.sesolve(H, psi_0, t_arr)

print(res.states)

[Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.99211955-0.08842141j]
 [0.00788044+0.08842141j]
 [0.        +0.j        ]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.96872663-0.17405559j]
 [0.0312734 +0.17405559j]
 [0.        +0.j        ]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.93055863-0.25420318j]
 [0.06944147+0.25420318j]
 [0.        +0.j        ]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j       ]
 [0.87881871-0.3263378j]
 [0.12118149+0.3263378j]
 [0.        +0.j       ]], Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.81513782-0.38818564j]
 [0.18486253+0.388185

In [20]:
psi = res.states[0]



Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]